name = "AlgorithmicAllocation"
uuid = "469123ea-c804-4113-a313-1af95b35a827"
authors = ["Will Tebbutt <will.tebbutt@invenialabs.co.uk> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
